//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRGRApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionOfRequest
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int work_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Work Work { get; set; }
    }
}
